server:
  port: 9002
dubbo:
  application:
    name: hello-consumer
  registry:
    protocal: zookeeper
    address: zookeeper://10.86.32.93:2181
  scan:
    base-packages: com.example.controller


spring:
  application:
    name: hello-consumer
  boot:
    admin:
      client:
        url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS